// mindfulness.js
import { store, todayISO } from '../storage.js';
let mindTimer=null, mindPlaying=false, mindElapsed=0, mindTotal=0, mindCtx=null, mindOsc=null;

function formatTime(ms){ const s=Math.floor(ms/1000), m=Math.floor(s/60); return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }

export function mindStart(){ if (mindPlaying) return; const minutes = Math.max(3, parseInt(document.getElementById('mindMinutes')?.value,10)||10); mindTotal = minutes*60*1000; const start = Date.now()-mindElapsed; mindPlaying=true; const tick=()=>{ if (!mindPlaying) return; mindElapsed = Date.now()-start; if (mindElapsed >= mindTotal){ mindStop(true); return; } document.getElementById('mindTime') && (document.getElementById('mindTime').textContent = formatTime(mindElapsed)); document.getElementById('mindProgress') && (document.getElementById('mindProgress').style.width = `${(mindElapsed/mindTotal)*100}%`); mindTimer = setTimeout(tick, 100); }; tick(); if (document.getElementById('mindAudio')?.checked) startAmbience(); }
export function mindPause(){ mindPlaying=false; clearTimeout(mindTimer); stopAmbience(); }
export function mindReset(){ mindPause(); mindElapsed=0; document.getElementById('mindTime') && (document.getElementById('mindTime').textContent='00:00'); document.getElementById('mindProgress') && (document.getElementById('mindProgress').style.width='0%'); }
export function mindStop(done=false){ mindPlaying=false; clearTimeout(mindTimer); stopAmbience(); if (done){ const type=document.getElementById('mindType')?.value||'breath'; const entry={ title:(type==='breath'?'Mindful Breathing': type==='body'?'Body Scan': type==='focus'?'Focus & Clarity':'Relax for Sleep'), duration: Math.round(mindTotal/60000), category:type, completedOn: todayISO(), reflection:'—' }; const log=store.get('mindLog',[]); log.unshift(entry); store.set('mindLog', log); renderMindLog(); } }
function startAmbience(){ const Ctx = window.AudioContext || window.webkitAudioContext; if (!Ctx) return; mindCtx = new Ctx(); mindOsc = mindCtx.createOscillator(); const gain = mindCtx.createGain(); mindOsc.type='sine'; mindOsc.frequency.value = 396; gain.gain.value = 0.01; mindOsc.connect(gain).connect(mindCtx.destination); mindOsc.start(); }
function stopAmbience(){ if (mindOsc){ mindOsc.stop(); mindOsc.disconnect(); mindOsc=null; } if (mindCtx){ mindCtx.close(); mindCtx=null; } }
export function renderMindLog(){ const ul = document.getElementById('mindLog'); if (!ul) return; ul.innerHTML=''; const log = store.get('mindLog',[]); log.slice(0,20).forEach(m=>{ const li=document.createElement('li'); li.textContent=`${m.completedOn} — ${m.title} (${m.duration} min)`; ul.appendChild(li); }); }
export function bookmarkMind(){ const type=document.getElementById('mindType')?.value||'breath'; const minutes = Math.max(3, parseInt(document.getElementById('mindMinutes')?.value,10)||10); const list = store.get('mindBookmarks',[]); const entry = { title: document.querySelector('#mindType option:checked')?.textContent||'Mindful', category:type, duration: minutes }; list.unshift(entry); store.set('mindBookmarks', list); renderMindBookmarks(); }
export function renderMindBookmarks(){ const ul = document.getElementById('mindBookmarks'); if (!ul) return; ul.innerHTML=''; const list = store.get('mindBookmarks',[]); list.slice(0,10).forEach(b=>{ const li=document.createElement('li'); li.textContent = `${b.title} — ${b.duration} min`; ul.appendChild(li); }); }